# Config file for automatic testing at travis-ci.com

language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SukiCZ
  password:
    secure: FtILNWLonPsiWH/t6qIDrAmic+4X6qB0O957QJWI6b0Lmtx8eOYWQ0ryHpcIvL+6w851VIWOhQXKtJL5+YtGKH+1p7Wd7kwiqMsDf2RelL7ye3keUg4q3wqEyRAQ4DVdSIDLVFYZ1tzzl2Ay9gfshu/KoE9fA/4xz0pkSffRHWEmedBt0+Yy5LG+UH6hvgmgx1VyHfmJ/vtpyoCkaBQ/84CxCVbwoeYA+2RM38B8bSijMvfWk6NRusFLU1y5v6M+f7GcEfgZ7VvQzqd9sdVRsC24yTx2Par5Er9Amd7u3rg4RCiRbFp8AjfGeI+2f/6RsxEHqh6AmH6Jboj8/8b6ZqtDBB4muw0hkwQdPNQs26nXRRASGhzG81uRS8MHFv4Ued0KIsO/wEX4XbHmqm8MuYkrBnT4SHNDrWmcaSjx7k5b23QG/kFeUisgmVQhW9c8WPBvD2qZMPbXLmy7R7BA/j3ds8dCe1K4DE+w4C+s7XR5QYstlfuSO+uhc3HwFumomisRsYUeyk5hDWCgamPOqS80VlwV3+l6Yy1ZFdfkEUXkzFnor4mOch9fhbwCztPr0bZ43ezLZU4s8IP2z6PERyNStVA4IFa/dxb8vhADVvu5MA9ofit3YZYPI07dudXSiX0mbQZU3woUHkUr51frBpW6sicv0hTOcvy2jwEhWWc=
  on:
    tags: true
    repo: SukiCZ/justice
    python: 3.8
